### ISSUE TITLE
Cross compiling for Android

### ISSUE THREAD

**Issue by palmerc** [drbenmorgan/BoostBuilder#1]
Cross compiling support for Android would be a great addition.

**Comment by drbenmorgan** [comment]
This project isn't being actively developed anymore - at least, my need for it is mostly gone with good packaging for Boost on desktop Unix systems from spack, brew and others, plus CMake's FindBoost module providing imported targets since version 3.5. 

PRs are welcome of course, but might be better to fork and adapt to your specific needs as I don't use Android so cannot develop/test directly.

**Comment by palmerc** [comment]
Thanks for the feedback. I am personally using boost for native builds the same way you are, but cross-compiling boost is a bit of a pain and a cmake solution similar to this one feels like it might be the right way to go. Again thanks for responding so quickly.
